### ISSUE TITLE
Deserialization error upon creating DeviceServer

### ISSUE THREAD

**Issue by bluewalk** [Sycade/BunqApi#1]
Hi there (hoi!),

I am trying to use your API client to retrieve just my transactions from bunq, just to test everything quickly.

At the following code I'm getting a serialization error:
```csharp
var deviceServer = await bunq.DeviceServers.CreateAsync("Bluewalk test", apiKey, installation.Token);
```

> Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Sycade.BunqApi.Model.Error' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

> To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.

**Update 09:17**
The error that I'm receiving isn't parsed correctly:
> parsedObject["Error"]
{[
  {
    "error_description": "User credentials are incorrect. Incorrect API key or IP address.",
    "error_description_translated": "User credentials are incorrect. Incorrect API key or IP address."
  }
]}

**Comment by bluewalk** [comment]
API Errors daargelaten (van het juiste ip adres het request sturen) zijn er andere deserialization errors bij `GetEntities`

> System.ArgumentException: 'Requested value 'USE_RESPONSE_NATIVE_COMMENT' was not found.'

**Comment by bluewalk** [comment]
Ok, geen reactie... We laten dit project maar vallen

**Comment by mlowijs** [comment]
Hi Délano,

Sorry voor het gebrek aan reactie.

Omdat bunq zelf SDKs uitgegeven heeft voor o.a. .NET, heeft het voor mij weinig zin om hieraan verder te werken.

Michiel

**Comment by bluewalk** [comment]
Precies, mede ook om die reden gesloten :)
